# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- id: ormb
  main: ./cmd/ormb/main.go
  binary: ormb
- id: ormb-storage-initializer
  main: ./cmd/ormb-storage-initializer/main.go
  binary: ormb-storage-initializer
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: caicloud
    name: ormb
# dockers:
#   - goos: linux
#     goarch: amd64
#     builds:
#     - ormb
#     dockerfile: build/ormb/Dockerfile
#     # Templates of the Docker image names.
#     image_templates:
#     - "clvoss/clever-ormb:latest"
#     - "clvoss/clever-ormb:{{ .Tag }}"
#     - "clvoss/clever-ormb:v{{ .Major }}"
